#include "rational.h"
#include <iostream>
#include <sstream>

int main()
{
	using namespace std;
	Rational ratio(1, 2);
	Rational ratio1(3, 10);
	Rational ratio2(1, 6);
	Rational ratio3(2, 4);
	Rational ratio4(5, 6);
	Rational ratio5(4, 7);
	int int1 = 2;
	int int2 = -2;
	cout << "ratio = " << ratio << endl;
	cout << "ratio1 = " << ratio1 << endl;
	cout << "ratio2 = " << ratio2 << endl;
	cout << "ratio3 = " << ratio3 << endl;
	cout << "ratio4 = " << ratio4 << endl;
	cout << "ratio5 = " << ratio5 << endl;
	bool m = ratio1 == ratio2;
	cout << "ratio1 == ratio2 : " << m << endl;
	m = ratio == ratio;
	cout << "ratio == ratio : " << m << endl;
	m = ratio != ratio;
	cout << "ratio != ratio : " << m << endl;
	m = ratio1 != ratio3;
	cout << "ratio1 != ratio3 : " << m << endl;
	m = ratio1 > ratio3;
	cout << "ratio1 > ratio3 : " << m << endl;
	m = ratio4 > ratio2;
	cout << "ratio4 > ratio2 : " << m << endl;
	m = ratio1 > ratio1;
	cout << "ratio1 > ratio1 : " << m << endl;
	m = ratio3 >= ratio3;
	cout << "ratio3 >= ratio3 : " << m << endl;
	m = ratio2 >= ratio4;
	cout << "ratio2 >= ratio4 : " << m << endl;
	m = ratio3 >= ratio1;
	cout << "ratio3 >= ratio1 : " << m << endl;
	m = ratio1 < ratio4;
	cout << "ratio1 < ratio4 : " << m << endl;
	m = ratio4 < ratio4;
	cout << "ratio4 < ratio4 : " << m << endl;
	m = ratio1 < ratio2;
	cout << "ratio1 < ratio2 : " << m << endl;
	m = ratio <= ratio;
	cout << "ratio <= ratio : " << m << endl;
	m = ratio1 <= ratio5;
	cout << "ratio1 <= ratio5 : " << m << endl;
	m = ratio4 <= ratio2;
	cout << "ratio4 <= ratio2 : " << m << endl;
	Rational sum = ratio + ratio1;
	cout << ratio << " + " << ratio1 << " -> " << sum << endl;
	cout << endl;
	sum = int1 + ratio2;
	cout << int1 << " + " << ratio2 << " -> " << sum << endl;
	cout << endl;
	sum = ratio1 + int1;
	cout << ratio1 << " + " << int1 << " -> " << sum << endl;
	cout << endl;
	cout << ratio3 << " += " << int1 << " -> ";
	ratio3 += int1;
	cout << ratio3 << endl;
	cout << endl;
	cout << ratio3 << " += " << ratio1 << " -> ";
	ratio3 += ratio1;
	cout << ratio3 << endl;
	cout << endl;
	Rational diff = ratio3 - ratio1;
	cout << ratio3 << " - " << ratio1 << " -> " << diff << endl;
	cout << endl;
	diff = int1 - ratio3;
	cout << int1 << " - " << ratio3 << " -> " << diff << endl;
	cout << endl;
	diff = ratio4 - int1;
	cout << ratio4 << " - " << int1 << " -> " << diff << endl;
	cout << endl;
	cout << ratio3 << " -= " << ratio1 << " -> ";
	ratio3 -= ratio1;
	cout << ratio3 << endl;
	cout << endl;
	cout << ratio1 << " -= " << int1 << " -> ";
	ratio1 -= int1;
	cout << ratio1 << endl;
	cout << endl;
	Rational mult = ratio2 * ratio1;
	cout << ratio2 << " * " << ratio1 << " -> " << mult << endl;
	cout << endl;
	mult = int1 * ratio3;
	cout << int1 << " * " << ratio3 << " -> " << mult << endl;
	cout << endl;
	mult = ratio4 * int1;
	cout << ratio4 << " * " << int1 << " -> " << mult << endl;
	cout << endl;
	cout << ratio1 << " *= " << ratio4 << " -> ";
	ratio1 *= ratio4;
	cout << ratio1 << endl;
	cout << endl;
	cout << ratio1 << " *= " << int2 << " -> ";
	ratio1 *= int2;
	cout << ratio1 << endl;
	cout << endl;
	Rational quot = ratio4 / ratio2;
	cout << ratio4 << " / " << ratio2 << " -> " << quot << endl;
	cout << endl;
	quot = int2 / ratio3;
	cout << int2 << " / " << ratio3 << " -> " << quot << endl;
	cout << endl;
	quot = ratio5 / int1;
	cout << ratio5 << " / " << int1 << " -> " << quot << endl;
	cout << endl;
	cout << ratio5 << " /= " << int2 << " -> ";
	ratio5 /= int2;
	cout << ratio5 << endl;
	cout << endl;
	cout << ratio5 << " /= " << ratio << " -> ";
	ratio5 /= ratio;
	cout << ratio5 << endl;
	cout << endl;
	char exit;
	cin >> exit;
	return 0;
}